### PR TITLE
Add secrets version printout

### PR DESCRIPTION
**Pull request by kwozyman**

### CODE REVIEW

**Comment by sagidayan** [comment]
/lgtm 
🤞🏽

**Comment by kpouget** [comment]
FYI, `cat /var/run/secrets/version` this shouldn't work _anymore_, 
it is a potential leak, so the CI censors it
(there was a bug that allowed ci-artifacts to print it until recently, eg 1months ago, but it should be all fixed now)

**Comment by kpouget** [comment]
if you want to do it (because it's safe), then you need to modify the content, so that it's not identical to the secret in the vault,
like modifying some chars in the middle of the text

**Comment by kwozyman** [comment]
> this shouldn't work anymore

I can confirm it does not :) I wanted to see if my secrets have been synchronized as I keep having problems with this

**Pull request merged**
