### PR TITLE
updates to use dependency packages locally

### PR DESCRIPTION
**Pull request by wabouhamad**
Updated imports to use local dependency modules in the new pkg directory:

  - pkg/clients/clients.go
  - pkg/configmap/configmap.go
  - pkg/deployment/deployment.go
  - pkg/deployment/list.go
  - pkg/machine/machineset.go
  - pkg/machine/machinesetlist.go
  - pkg/msg/msg.go
  - pkg/namespace/list.go
  - pkg/namespace/namespace.go
  - pkg/nfd/nodefeaturediscovery.go
  - pkg/nodes/list.go
  - pkg/nodes/node.go
  - pkg/nodes/nodetypes.go
  - pkg/nvidiagpu/clusterpolicy.go
  - pkg/olm/catalogsource.go
  - pkg/olm/catalogsourcelist.go
  - pkg/olm/clusterserviceversion.go
  - pkg/olm/clusterserviceversionlist.go
  - pkg/olm/installplan.go
  - pkg/olm/installplanlist.go
  - pkg/olm/operatorgroup.go
  - pkg/olm/packagemanifest.go
  - pkg/olm/packagemanifestlist.go
  - pkg/olm/subscription.go
  - pkg/pod/container.go
  - pkg/pod/list.go
  - pkg/pod/network.go
  - pkg/pod/pod.go

### CODE REVIEW

**Comment by ybettan** [comment]
I have a few questions regarding this PR:
1. Why do we need all those packages locally?
2. What happens when we need to update a package? are we only going to update it locally and leave `eco-goinfra` "out of sync"?
3. At some point, this effort will probably be extended to other partners as well, what will happen then? Are we going to also import all the packages to the new repo?
4. If the reason for moving them to this repo is faster development, wouldn't it be better if we move them to `eco-gotest` instead (as we have admin access to `eco-gotest` and we can merge fast)?

**Comment by wabouhamad** [comment]
@ybettan one main issue here is the "clients" package from eco-goinfra import all the APIs used by eco-gotests contributors in all their projects, and many we do not need, and have dependencies on specific module versions and some are no longer available, they have to be excluded.  They are also on golang v1.22 and we are still on v1.20.  

The packages in eco-goinfra also depend on many modules on specific versions and they had many replace statements in their go.mod file.  I needed to update the API version for GPU operator for my GPU Operator Update test case I am working on, which depends on this PR, and to do that in eco-goinfra where the packages were previously located, would require several reviews and making sure that the dependencies we are pulling from kubernetes or openshift do not break other projects used by eco-gotests team.  

By having the bare-bone minimal set of packages we need locally, we are better suited to control the versions of the modules and APIs we need, we can merge them faster without impacting other teams.  And yes we will be out of sync with eco-goinfra but we can focus our efforts here on Nvidia CI and what impacts Nvidia projects.

**Pull request merged**
